cle.configuration.application.setEndpointHost('http://localhost:9950');
cle.configuration.category.setEndpointHost('http://localhost:9950');
cle.configuration.exception.setEndpointHost('http://localhost:9950');
cle.configuration.interfaceConfig.setEndpointHost('http://localhost:9950');
cle.configuration.procedure.setEndpointHost('http://localhost:9950');
cle.configuration.rendering.setEndpointHost('http://localhost:9950');
cle.configuration.severity.setEndpointHost('http://localhost:9950');
cle.configuration.type.setEndpointHost('http://localhost:9950');
cle.exception.setEndpointHost('http://localhost:9950');
cle.log.setEndpointHost('http://localhost:9950');
cle.login.setEndpointHost('http://localhost:9950');
cle.roles.setEndpointHost('http://localhost:9950');
cle.security.setEndpointHost('http://localhost:9950');

/*
cle.configuration.application.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.category.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.exception.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.interfaceConfig.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.procedure.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.rendering.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.severity.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.configuration.type.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.exception.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.log.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.login.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.roles.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.security.setEndpointHost('http://demohost81.na.tibco.com:9950');
cle.charts.setEndpointHost('http://demohost81.na.tibco.com:9950');
*/

/*
cle.configuration.category.setEndpointUrl();
cle.configuration.exception.setEndpointUrl();
cle.configuration.interfaceConfig.setEndpointUrl();
cle.configuration.procedure.setEndpointUrl();
cle.configuration.rendering.setEndpointUrl();
cle.configuration.severity.setEndpointUrl();
cle.configuration.type.setEndpointUrl();
cle.exception.setEndpointUrl();
cle.log.setEndpointUrl();
cle.login.setEndpointUrl();
cle.roles.setEndpointUrl();
cle.security.setEndpointUrl();
*/

