--===============================================
--   APPLICATIONS
--===============================================
INSERT INTO APPLICATIONS
            (applicationid, NAME, description)
     VALUES ('Test', 'Test CLE', 'Test CLE application');

--===============================================
--   EXCEPTIONCATEGORY
--===============================================
INSERT INTO EXCEPTIONCATEGORY
	(applicationid, ID, NAME,description)
	VALUES ('Test', categoryid.nextval, 'System', 'System Exceptions, such as timeout, db outage.');
	
INSERT INTO EXCEPTIONCATEGORY
	(applicationid, ID, NAME,description)
	VALUES ('Test', categoryid.nextval, 'Business', 'Business Exceptions such as data issue, rule violation.');
	
--===============================================
--   EXCEPTIONTYPE
--===============================================

Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'CatchAll','Generic Catch All Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'InvalidData','Invalid Data Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Unknown','Unknown Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Resource Unavailable','Resource Unavailable Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Timeout','Timeout Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Login','Login Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Connection','Connection Exception');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'Duplicate','Duplicate transaction data');
Insert into EXCEPTIONTYPE (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',TYPEID.nextval,'InvalidFormat','Invalid Format Exception');


--===============================================
--   	EXCEPTIONSEVERITY
--===============================================

Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'CRITICAL','Condition that affects service has occurred, Immediate Corrective Action required');
Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'HIGH','Problem with a relatively high severity level has occurred, It is likely that normal use of the object will be impeded');
Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'MEDIUM','Problem with a relatively low severity level has occurred, It is unlikely that normal use of the object will be impeded');
Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'LOW','Problem that affects service will or could occur, Diagnostic and corrective action is recommended');
Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'NORMAL','Message output is normal');
Insert into EXCEPTIONSEVERITY (APPLICATIONID,ID,NAME,DESCRIPTION) values ('Test',SEVERITYID.nextval,'UNKNOWN','Severity level cannot be determined');

--===============================================
--   	EXCEPTIONPROCEDURE
--===============================================

--===============================================
--   	BW EXCEPTIONCONFIG
--===============================================
--Common BW Exceptions

Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','TECHNICAL-100','FailedSourceIPValidation',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='System' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='Connection' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='CRITICAL' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','TECHNICAL-111','Invalid Transaction From Trading Partner',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='System' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='Unknown' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='LOW' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','FUNC-TestBW-121','Source Confirmation Fail',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='Business' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='Duplicate' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='LOW' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','FUNC-TestBW-001','Invalid Data Error',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='Business' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='InvalidData' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='HIGH' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','TECHNICAL-777','Generic Technical Exception',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='System' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='CatchAll' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='HIGH' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','TECHNICAL-101','Resource Unavailable',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='System' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='Resource Unavailable' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='HIGH' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','FUNC-TestBW-002','Incorrect Format Error',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='Business' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='InvalidFormat' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='HIGH' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);
Insert into EXCEPTIONCONFIG (APPLICATIONID,EXCEPTIONCODE,DESCRIPTION,CATEGORYID,TYPEID,SEVERITYID,REPLYDESTINATION,ROLENAME,PROCEDUREID,NOTIFICATIONCHNL,EMAILTO,EMAILCC,EXCEPTIONTTL,RESOLVEDELAYINTERVAL,EVENTTYPE) values ('Test','TECHNICAL-102','Duplicate Transaction',(SELECT EXCEPTIONCATEGORY.ID FROM EXCEPTIONCATEGORY WHERE NAME='System' AND APPLICATIONID='Test'),(SELECT EXCEPTIONTYPE.ID FROM EXCEPTIONTYPE WHERE NAME='Duplicate' AND APPLICATIONID='Test'),(SELECT EXCEPTIONSEVERITY.ID FROM EXCEPTIONSEVERITY WHERE NAME='HIGH' AND APPLICATIONID='Test'),null,null,null,'ZBS.INTEGRATION.CLE.NOTIFICATION','Bhanu.Nalluri@zimmer.com',null,10,0,null);


--================================================
--        INTERFACE CONFIG
--================================================
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','846Inbound','InventoryAdvice','Logical','Zimmer','Exel','DCS','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','856Inbound','AdvanceShipmentNotice','Logical','Zimmer','Exel','DCS','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','856Outbound','AdvanceShipmentNotice','Logical','Zimmer','DCS','Exel','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','888Outbound','MaterialMasterItemMaintenance','Logical','Zimmer','DCS','Exel','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','940Outbound','WarehouseShippingOrder','Logical','Zimmer','DCS','Exel','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','944Inbound','WarehouseStockTransferReceipt','Logical','Zimmer','Exel','DCS','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','947Inbound','InventoryStatusChangeOrAdjustment','Logical','Zimmer','Exel','DCS','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','947Outbound','InventoryStatusChangeOrAdjustment','Logical','Zimmer','DCS','Exel','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','997Inbound','FunctionalAcknowledgement','Logical','Zimmer','Exel','DCS','N','Medium',null,null,'Active',null);
Insert into INTERFACECONFIG (APPLICATIONID,INTERFACEID,INTERFACENAME,INTERFACETYPE,OWNER,SOURCESYSTEM,TARGETSYSTEM,DBUSE,TRANSCOMPLEXITY,DESCRIPTION,PARENTID,STATUS,PROTOCOL) values ('Test','997Outbound','FunctionalAcknowledgement','Logical','Zimmer','DCS','Exel','N','Medium',null,null,'Active',null);
